name = "NQCBase"
uuid = "78c76ebc-5665-4934-b512-82d81b5cbfb7"
authors = ["James Gardner <james.gardner1421@gmail.com> and contributors"]
version = "0.1.5"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
ExtXYZ = "352459e4-ddd7-4360-8937-99dcb397b478"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
Distances = "0.10"
ExtXYZ = "0.1"
PeriodicTable = "1"
PyCall = "1"
Requires = "1"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PyCall", "Test", "SafeTestsets"]
